/**
 * SecurePark Web App - Pass Rules & System Settings View
 *
 * Allows administrators to configure campus gate policies, notably the
 * expiration validity duration for single-visit temporary visitor QR passes.
 * This fixed rule is fetched and respected by the gate guard mobile app.
 */
(function () {
  'use strict';

  const $ = (id) => document.getElementById(id);
  let currentSettings = {
    visitor_pass_validity_hours: 8
  };

  async function loadSettings() {
    if (!window.ApiClient || !ApiClient.hasToken()) return;
    try {
      const data = await ApiClient.getSettings();
      if (data) {
        currentSettings = Object.assign(currentSettings, data);
        renderSettings();
      }
    } catch (err) {
      console.warn('[Settings] Failed to fetch settings:', err.message);
    }
  }

  function renderSettings() {
    const hours = Number(currentSettings.visitor_pass_validity_hours) || 8;
    const input = $('settingVisitorHours');
    if (input) input.value = hours;

    const badge = $('settingActiveRuleBadge');
    if (badge) {
      badge.textContent = `${hours} Hours Validity`;
    }

    const desc = $('settingActiveRuleDesc');
    if (desc) {
      desc.textContent = `All temporary visitor QR passes generated by guards at campus gates will expire automatically ${hours} hour${hours === 1 ? '' : 's'} after issuance.`;
    }

    // Highlight preset chip
    document.querySelectorAll('[data-hours-preset]').forEach(btn => {
      const preset = Number(btn.getAttribute('data-hours-preset'));
      if (preset === hours) {
        btn.classList.add('bg-ncst-navy', 'text-white', 'border-ncst-navy');
        btn.classList.remove('bg-white', 'text-slate-700', 'border-slate-200');
      } else {
        btn.classList.remove('bg-ncst-navy', 'text-white', 'border-ncst-navy');
        btn.classList.add('bg-white', 'text-slate-700', 'border-slate-200');
      }
    });
  }

  async function saveSettings(e) {
    if (e) e.preventDefault();
    const input = $('settingVisitorHours');
    const hours = parseInt(input ? input.value : '8', 10);

    if (isNaN(hours) || hours < 1 || hours > 72) {
      if (window.SPAlert) {
        SPAlert.error({
          title: 'Invalid Expiration Duration',
          text: 'Temporary visitor pass validity must be between 1 and 72 hours.'
        });
      } else {
        alert('Visitor pass validity must be between 1 and 72 hours.');
      }
      return;
    }

    const confirmed = window.SPAlert
      ? await SPAlert.confirm({
          title: 'Update Pass Expiration Rule?',
          text: `Change temporary visitor pass validity to ${hours} hour${hours === 1 ? '' : 's'}? The guard mobile application will automatically fetch and enforce this fixed duration rule.`,
          confirmText: 'Save Rule',
          icon: 'question'
        })
      : confirm(`Change visitor pass validity to ${hours} hours?`);

    if (!confirmed) return;

    const btn = $('settingSaveBtn');
    if (btn) btn.disabled = true;

    try {
      const res = await ApiClient.updateSettings({
        visitor_pass_validity_hours: hours
      });
      currentSettings.visitor_pass_validity_hours = hours;
      renderSettings();

      if (window.SPAlert) {
        SPAlert.success({
          title: 'Pass Rule Updated',
          text: `Visitor pass expiration is now set to ${hours} hour${hours === 1 ? '' : 's'}. Mobile terminals will sync this constant rule.`,
          timer: 2500
        });
      } else if (window.SP && SP.showToast) {
        SP.showToast(`Visitor pass expiration updated to ${hours} hours.`, 'success');
      }
    } catch (err) {
      if (window.SPAlert) {
        SPAlert.error({
          title: 'Failed to Save Settings',
          text: err.message
        });
      } else if (window.SP && SP.showToast) {
        SP.showToast(`Error saving settings: ${err.message}`, 'error');
      }
    } finally {
      if (btn) btn.disabled = false;
    }
  }

  // Setup event listeners
  document.addEventListener('sp:app-ready', () => {
    if (window.SP && SP.registerView) {
      SP.registerView('settingsView', $('navSettingsBtn'), loadSettings);
    }

    const form = $('settingsForm');
    if (form) form.addEventListener('submit', saveSettings);

    const saveBtn = $('settingSaveBtn');
    if (saveBtn) saveBtn.addEventListener('click', saveSettings);

    // Preset buttons (2h, 4h, 8h, 12h, 24h)
    document.querySelectorAll('[data-hours-preset]').forEach(btn => {
      btn.addEventListener('click', () => {
        const hours = btn.getAttribute('data-hours-preset');
        const input = $('settingVisitorHours');
        if (input) input.value = hours;
        currentSettings.visitor_pass_validity_hours = Number(hours);
        renderSettings();
      });
    });
  });

  // Export for testing
  window.SPSettings = { load: loadSettings, save: saveSettings };
})();
